export interface StaffJWTClaims {
	role: 'owner' | 'manager' | 'barber';
	exp: number;
	staff_member_id: string;
	name: string;
	location_id: string;
	tenant_id: string;
}

export function decodeToken(token: string): StaffJWTClaims | null {
	try {
		const parts = token.split('.');
		if (parts.length !== 3) return null;
		const payload = parts[1];
		const base64 = payload.replace(/-/g, '+').replace(/_/g, '/');
		const raw =
			typeof atob !== 'undefined' ? atob(base64) : Buffer.from(base64, 'base64').toString('binary');
		const utf8 = decodeURIComponent(
			raw
				.split('')
				.map((c) => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
				.join('')
		);
		return JSON.parse(utf8) as StaffJWTClaims;
	} catch {
		return null;
	}
}

export function isTokenExpired(claims: StaffJWTClaims): boolean {
	return claims.exp * 1000 < Date.now() + 5000;
}

export function getApiBase(platform?: any): string {
	if (platform?.env?.PUBLIC_API_BASE) {
		return platform.env.PUBLIC_API_BASE;
	}
	if (typeof process !== 'undefined' && process.env?.PUBLIC_API_BASE) {
		return process.env.PUBLIC_API_BASE;
	}
	if (typeof import.meta !== 'undefined' && import.meta.env?.PUBLIC_API_BASE) {
		return import.meta.env.PUBLIC_API_BASE;
	}
	return 'https://api.barberbase.in';
}

export class ApiClient {
	private baseUrl: string;
	private accessToken?: string;

	constructor(accessToken?: string, platform?: any) {
		this.baseUrl = getApiBase(platform);
		this.accessToken = accessToken;
	}

	async request<T>(path: string, options: RequestInit = {}): Promise<T> {
		const url = `${this.baseUrl}${path}`;
		const headers = new Headers(options.headers);
		if (this.accessToken) {
			headers.set('Authorization', `Bearer ${this.accessToken}`);
		}
		if (options.body && !(options.body instanceof FormData)) {
			headers.set('Content-Type', 'application/json');
		}

		const response = await fetch(url, {
			...options,
			headers
		});

		if (!response.ok) {
			let errorData;
			try {
				errorData = await response.json();
			} catch {
				errorData = { message: response.statusText };
			}
			throw { status: response.status, data: errorData };
		}

		const text = await response.text();
		return (text ? JSON.parse(text) : {}) as T;
	}

	get<T>(path: string, options?: Omit<RequestInit, 'method'>) {
		return this.request<T>(path, { ...options, method: 'GET' });
	}

	post<T>(path: string, body?: any, options?: Omit<RequestInit, 'method' | 'body'>) {
		return this.request<T>(path, {
			...options,
			method: 'POST',
			body: body ? JSON.stringify(body) : undefined
		});
	}

	patch<T>(path: string, body?: any, options?: Omit<RequestInit, 'method' | 'body'>) {
		return this.request<T>(path, {
			...options,
			method: 'PATCH',
			body: body ? JSON.stringify(body) : undefined
		});
	}

	delete<T>(path: string, options?: Omit<RequestInit, 'method'>) {
		return this.request<T>(path, { ...options, method: 'DELETE' });
	}
}

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/public/locations/{location_slug}/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get live shop status and queue length
		 * @description Called on page load and by AI agent to check if shop is open and queue state.
		 *     Response cached at Cloudflare edge for 15 seconds (stale-while-revalidate).
		 *     This is the first call when customer lands on the shop page.
		 */
		get: operations['getLocationStatus'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/locations/{location_id}/service-catalog': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get full hierarchical service catalog
		 * @description Returns service tree: categories → groups → variants.
		 *     Cached at Cloudflare edge for 1 hour. Invalidated on service update.
		 *     Used by: web service selector, AI agent tool call.
		 *     Filter by gender to reduce payload on simple shops.
		 */
		get: operations['getServiceCatalog'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/locations/{location_id}/service-catalog/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Search service variants by name
		 * @description Fuzzy search across variant names and group names.
		 *     Primary tool for AI agent to resolve customer intent to variant_id.
		 *     e.g. query="mid fade" returns Mid Fade variant with full context.
		 */
		get: operations['searchServiceVariants'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/locations/{location_id}/booking-options': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Resolve allowed entry methods for selected services
		 * @description Strictest-service-wins logic. Returns whether walk-in, appointment, or both
		 *     are available given the selected variant_ids and current shop state.
		 *     Called after customer finishes service selection before showing Join/Book buttons.
		 *     Also used by AI agent before calling join_queue or book_appointment.
		 */
		post: operations['resolveBookingOptions'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/locations/{location_id}/checkin-intents': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create a check-in intent for the WhatsApp JOIN handshake
		 * @description Called when the customer taps [Join via WhatsApp] after booking-options
		 *     returns walk_in in allowed_modes. Creates a checkin_intents row
		 *     (status='created') and returns a short token_code plus a wa.me deep link
		 *     pre-filled with "JOIN {LOCATION_SLUG} {TOKEN_CODE}".
		 *
		 *     Does NOT create a queue_entry. The queue_entry is created later by the
		 *     webhook worker when the customer's WhatsApp JOIN message arrives and the
		 *     token_code is resolved (10_customer_journey.md steps 4–7).
		 *
		 *     Intent snapshots shop_status at creation; closing-time rejection is decided
		 *     at resolution, not here. Each tap creates a new throwaway intent (no
		 *     idempotency key); unresolved intents expire in 23h.
		 *
		 *     Public + unauthenticated. Abuse-guarded by Cloudflare Turnstile at the edge
		 *     and golang.org/x/time/rate in the backend.
		 */
		post: operations['createCheckinIntent'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/locations/{location_id}/appointment-slots': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get available appointment time slots for a date
		 * @description Returns available slots given service durations and existing appointments.
		 *     Slots that would exceed closing time are not returned.
		 *     Used by web date picker and AI agent.
		 */
		get: operations['getAppointmentSlots'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/staff/request-otp': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Request WhatsApp OTP for staff login
		 * @description Staff enters phone number. Go calls Bhejna sending API.
		 *     Bhejna sends 6-digit OTP to staff's WhatsApp.
		 *     Rate limited: max 3 requests per phone per 10 minutes.
		 */
		post: operations['requestStaffOTP'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/staff/verify-otp': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify OTP and issue staff JWT */
		post: operations['verifyStaffOTP'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/staff/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Refresh access token using httpOnly refresh cookie
		 * @description Called automatically by SvelteKit BFF when access token expires (15 min TTL).
		 */
		post: operations['refreshStaffToken'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/queue/join': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Join the queue (walk-in)
		 * @description Called after customer completes service selection on the web UI and taps Confirm.
		 *     Idempotency key prevents duplicate joins on retry.
		 *
		 *     Identity resolution order:
		 *     1. If phone_number provided: lookup customer by (tenant_id, phone_number)
		 *     2. If not found: create new customer record
		 *     3. Store BSUID in customer_identities if provided
		 *
		 *     On success: creates visit + visit_services + queue_entry, fires outbox event
		 *     to send WhatsApp confirmation via Bhejna.
		 *
		 *     Returns signed magic_link_token valid for 23 hours.
		 */
		post: operations['joinQueue'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/appointments/book': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Book an appointment
		 * @description Books a time slot. Validates slot availability inside a transaction.
		 *     On success: creates appointment record, fires WhatsApp confirmation via outbox.
		 *     Appointment becomes a queue_entry only when customer checks in on the day.
		 */
		post: operations['bookAppointment'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/queue/my-status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get customer's live queue status
		 * @description Called on magic link page load and after SSE ping triggers a re-fetch.
		 *     Returns current position, estimated wait, and presence state.
		 *     This is the primary polling/fetch target after SSE ping.
		 */
		get: operations['getMyQueueStatus'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/queue/on-the-way': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Customer confirms they are heading to the shop
		 * @description Updates presence_state from remote/notified → on_the_way.
		 *     Triggers an SSE ping to the staff dashboard showing customer is coming.
		 *     No validation beyond session token. Customer self-declares.
		 */
		post: operations['confirmOnTheWay'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/queue/confirm-arrival': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Confirm physical arrival at the shop
		 * @description Transitions presence_state → arrived. Requires physical verification.
		 *
		 *     Methods:
		 *     - pin: Customer enters static location PIN shown at counter
		 *     - geolocation: Browser GPS within shop radius (auto-confirm, no input needed)
		 *     - nfc: Signed payload from NFC tag tap
		 *
		 *     Rate limited: max 5 attempts per queue_entry, 10 per IP per hour.
		 *     On success: is_dispatchable = true, SSE ping fires to staff dashboard.
		 */
		post: operations['confirmArrival'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/queue/cancel': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Customer cancels their own queue entry
		 * @description Allowed only when state = waiting or called.
		 *     Not allowed when state = in_progress.
		 *     Fires SSE ping to staff dashboard.
		 */
		post: operations['cancelMyEntry'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/queue/feedback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Submit post-service feedback
		 * @description Called from WhatsApp reply handler (via Bhejna webhook) or web rating page.
		 *     visit_id is embedded in the magic link token or outbox payload.
		 *     UNIQUE(visit_id) ensures one feedback per visit.
		 */
		post: operations['submitFeedback'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/stream/{location_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * SSE stream for queue version pings
		 * @description Go maintains this SSE connection in-memory via sync.Map keyed by location_id.
		 *
		 *     Events emitted:
		 *     - queue_changed: { type: "queue_changed", location_id: "uuid", queue_version: 184 }
		 *     - heartbeat: { type: "heartbeat" } every 30 seconds to keep connection alive
		 *
		 *     Client behaviour:
		 *     - On queue_changed: compare queue_version to local. If stale, fetch /queue/snapshot or /queue/my-status.
		 *     - On disconnect: reconnect with exponential backoff (1s, 2s, 4s, max 30s).
		 *     - Staff: persistent connection.
		 *     - Customer magic link: active while tab visible, pause on hidden, timeout after 4h idle.
		 *
		 *     Auth:
		 *     - Staff: StaffJWT query param (?token=...)
		 *     - Customer: CustomerSession query param (?t=...)
		 *     - Unauthenticated: connection rejected
		 */
		get: operations['subscribeToQueueStream'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/snapshot': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get full queue snapshot for staff dashboard
		 * @description Returns all active entries for today's queue session at the JWT's location_id.
		 *     Called on dashboard load and after SSE ping.
		 *     Ordered by: in_progress first, then called, then waiting by priority_group + sort_key.
		 */
		get: operations['getQueueSnapshot'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/call-next': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Call next dispatchable customer
		 * @description The primary barber action. Single tap moves the queue forward.
		 *
		 *     Transaction:
		 *     1. Lock queue_session FOR UPDATE
		 *     2. Find oldest dispatchable (state=waiting, is_dispatchable=true, presence=arrived)
		 *        filtered by barber routing mode and JWT barber_id
		 *     3. Assign barber, state → called, called_at = now()
		 *     4. Update barber status → cutting
		 *     5. Fire outbox: WhatsApp "your turn" message to customer
		 *     6. Increment queue_version, fire SSE ping via in-memory sync.Map
		 *     7. Commit
		 *
		 *     If no arrived customers available: returns 404 with waiting_remote_count
		 *     showing how many remote customers are on the way.
		 */
		post: operations['callNextCustomer'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/entries/{entry_id}/start': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Start service (called → in_progress)
		 * @description Normal flow: entry must be in state=called.
		 *     Direct start: if state=waiting and presence=arrived, atomically
		 *     sets called_at=now() and started_at=now() in one transition.
		 *     Updates barber status → cutting.
		 *     Fires SSE ping.
		 */
		post: operations['startService'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/entries/{entry_id}/complete': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Complete service and checkout (atomic)
		 * @description The CompleteVisitAndCheckout transaction. All-or-nothing.
		 *
		 *     1. Lock queue_session FOR UPDATE
		 *     2. Lock queue_entry FOR UPDATE
		 *     3. Lock visit FOR UPDATE
		 *     4. Validate state = in_progress
		 *     5. Finalize visit_charge
		 *     6. Insert visit_charge_line_items (services + any products)
		 *     7. Insert visit_payments
		 *     8. queue_entry.state → completed
		 *     9. visit.status → completed
		 *     10. customers: last_visit_at, visit_count++, lifetime_value_paise += total
		 *     11. staff_members.status → idle
		 *     12. Insert outbox_event: feedback_request (fires 30 min later)
		 *     13. Increment queue_version, fire SSE ping
		 *     14. COMMIT
		 */
		post: operations['completeService'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/entries/{entry_id}/skip': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Skip a customer (was called, not present)
		 * @description state → skipped. Customer remains visible on dashboard but not dispatchable.
		 *     Staff can later use /reactivate to put them back.
		 *     Fires SSE ping.
		 */
		post: operations['skipEntry'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/entries/{entry_id}/no-show': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Mark customer as no-show (was called, confirmed absent)
		 * @description Differs from skip: no-show is terminal for analytics.
		 *     state → no_show. Entry removed from active dispatch permanently.
		 *     WhatsApp message sent: "We missed you today."
		 */
		post: operations['markNoShow'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/entries/{entry_id}/reactivate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Reactivate a snoozed or skipped customer
		 * @description Used when a snoozed remote customer physically arrives.
		 *     Also used for skipped customers who return.
		 *     Re-inserts after current in_progress and called entries,
		 *     before waiting remote entries.
		 *     presence_state → arrived (staff confirms physical presence).
		 *     is_dispatchable → true.
		 *     Fires SSE ping.
		 */
		post: operations['reactivateEntry'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/entries/{entry_id}/confirm-arrival': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Staff confirms customer arrival (bypasses PIN)
		 * @description Used when customer forgot phone, is elderly, or cannot use PIN.
		 *     Staff authority overrides arrival verification.
		 *     presence_state → arrived, is_dispatchable → true.
		 *     Logged in arrival_attempts with method = staff.
		 */
		post: operations['staffConfirmArrival'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/entries/{entry_id}/reassign': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Reassign entry to a different barber
		 * @description Manager/owner role only. Used when barber has emergency mid-service.
		 *     Updates assigned_barber_id. Previous barber status → idle.
		 *     New barber status → cutting (if in_progress).
		 *     Fires SSE ping.
		 */
		post: operations['reassignBarber'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/queue/add-walkin': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Staff manually adds a walk-in customer
		 * @description Used when customer has no phone, no WhatsApp, or needs staff assistance.
		 *     Creates anonymous or named queue entry with presence_state = arrived.
		 *     No magic link issued (no phone). Staff tracks them verbally.
		 */
		post: operations['addWalkIn'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/shop/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current shop operational status */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Shop status */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {string} */
							shop_status?: 'open' | 'closing_soon' | 'temporarily_closed' | 'closed';
							/** @enum {string} */
							queue_session_status?: 'active' | 'paused' | 'ending' | 'closed';
							manual_override_active?: boolean;
							/** Format: date-time */
							override_expires_at?: string | null;
							/**
							 * @description Plain PIN shown to staff for whiteboard. Never exposed to customers.
							 * @example 4729
							 */
							arrival_pin?: string;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Change shop status (manual override)
		 * @description Staff or owner manually changes shop status.
		 *     If active queue entries exist when closing, modal_action required.
		 *
		 *     modal_action values:
		 *     - finish_remaining: stop new joins, serve existing queue to completion
		 *     - expire_remaining: immediately expire all waiting entries, notify customers
		 *     - pause: temporarily pause (requires expires_in_minutes)
		 */
		patch: operations['setShopStatus'];
		trace?: never;
	};
	'/staff/members': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List staff members for this location */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Staff list */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							staff?: components['schemas']['StaffMember'][];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/members/{staff_id}/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update barber operational status
		 * @description Barber sets themselves as on break, back from break, offline.
		 *     Owner can set any barber status.
		 */
		patch: operations['updateBarberStatus'];
		trace?: never;
	};
	'/staff/analytics/daily': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Daily revenue and visit summary
		 * @description Simple SQL aggregation. Not a ledger. Phase 1 hisab view.
		 *     Shows per-barber: visits completed, revenue collected.
		 *     Owner and manager roles only.
		 */
		get: operations['getDailyAnalytics'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/admin/setup': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Provision a new tenant + first location + owner (one-shot bootstrap)
		 * @description Platform operator endpoint. Atomically creates:
		 *       1. A tenant row (slug, name, owner_phone)
		 *       2. The tenant's first location (slug, name, address, timezone)
		 *       3. An owner staff_member (role=owner, phone=owner_phone) so the owner can
		 *          immediately request an OTP via POST /auth/staff/request-otp and log in.
		 *       4. Initializes the arrival PIN (6-digit crypto/rand, bcrypt-hashed).
		 *
		 *     StaffJWT cannot authorize this endpoint — no staff exist yet at setup time.
		 *     Gated by PlatformAdminKey (env: PLATFORM_ADMIN_KEY, constant-time compare).
		 *
		 *     Idempotency: duplicate tenant_slug, location_slug, or owner_phone → 409.
		 *     Phase 1: single location per tenant only (max_locations defaults to 1).
		 *     owner_phone must be E.164 and must not already exist in staff_members.
		 */
		post: operations['provisionTenant'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/admin/locations/{location_id}/services': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all services (full management view) */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					location_id: components['schemas']['UUIDv7'];
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Full service catalog for management */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ServiceCatalog'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a new service variant
		 * @description Also creates category/group if they don't exist.
		 */
		post: operations['createServiceVariant'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/admin/locations/{location_id}/services/{variant_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update a service variant
		 * @description Price/duration changes do NOT affect existing visit_services snapshots.
		 *     Snapshots are immutable. Only future bookings use new values.
		 */
		patch: operations['updateServiceVariant'];
		trace?: never;
	};
	'/admin/locations/{location_id}/arrival-pin/regenerate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Regenerate the static arrival PIN for this location
		 * @description Owner regenerates PIN if suspected of being shared externally.
		 *     New PIN must be written on the counter laminated card.
		 *     All existing queue entries that haven't arrived yet now require the new PIN.
		 */
		post: operations['regenerateArrivalPin'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/admin/staff': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Add a new staff member */
		post: operations['createStaffMember'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/webhooks/bhejna': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Receive normalized WhatsApp event from Bhejna
		 * @description CRITICAL: Write to webhook_events table BEFORE returning 200.
		 *     INSERT ... ON CONFLICT (source, external_event_id) DO NOTHING.
		 *     Always return 200 (idempotent). Never return 4xx to Bhejna (causes retries).
		 *
		 *     Async Go worker processes webhook_events WHERE status = 'pending'
		 *     using SKIP LOCKED for safe parallel processing.
		 *
		 *     Handled event_types:
		 *     - message.received: Customer joins queue, replies to prompts, sends OTP
		 *     - flow.completed: WhatsApp Flow form submission (future)
		 *     - message.status: Delivery receipts (for notification tracking)
		 */
		post: operations['receiveBhejnaWebhook'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/agent/locations/{location_id}/info': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * [TOOL] Get shop info and live queue status
		 * @description Combined tool for AI agent. Returns everything needed to answer
		 *     "Is Star Salon open?", "How long is the wait?", "What services do they have?"
		 *     in a single call.
		 */
		get: operations['agentGetShopInfo'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/agent/queue/join': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * [TOOL] Join queue on behalf of customer
		 * @description AI agent calls this after resolving customer intent to variant_ids.
		 *     Identical logic to /queue/join but with initiated_via = ai_agent.
		 *     phone_number is required (agent has it from conversation context).
		 */
		post: operations['agentJoinQueue'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/agent/appointments/book': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * [TOOL] Book appointment on behalf of customer
		 * @description Agent version of /appointments/book. Same logic, same response.
		 */
		post: operations['agentBookAppointment'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/agent/customer/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * [TOOL] Get customer's current queue or appointment status
		 * @description Agent calls this when customer asks "What's my token number?" or
		 *     "How long until my turn?" in WhatsApp conversation.
		 */
		get: operations['agentGetCustomerStatus'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/agent/customer/cancel': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * [TOOL] Cancel customer's queue entry
		 * @description Agent calls this when customer says "Cancel my booking"
		 */
		post: operations['agentCancelEntry'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/push/subscribe': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Register or update a Web Push subscription for this staff member
		 * @description Called from the dashboard after Notification.permission is granted.
		 *     Stores the W3C PushSubscription on the staff_members row (latest wins).
		 *     Overwrites any previous subscription — one subscription per staff member.
		 *     See: 16_web_push_service_worker.md — "Registration Flow"
		 */
		post: operations['subscribePush'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/staff/push/call-next': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Advance the queue from a lock-screen notification action
		 * @description Called by the Service Worker background fetch when the barber taps the
		 *     "NEXT CLIENT" action button on the push notification. Authenticates via
		 *     PushActionToken (not StaffJWT — JWT expires mid-haircut, see Law 18).
		 *
		 *     Executes the same call-next domain function as POST /staff/queue/call-next.
		 *     The queue_sessions FOR UPDATE lock serializes concurrent calls from multiple
		 *     devices (Law 1). Routing mode is respected (pooled/hybrid/barber_specific).
		 *
		 *     Service Worker MUST update the notification on every response — including
		 *     errors — so the barber always sees current queue state (see Law 18 error
		 *     handling contract in 16_web_push_service_worker.md).
		 */
		post: operations['pushCallNext'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/admin/locations/{location_id}/whatsapp/connect': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Connect a shop's own WABA (Mode B onboarding)
		 * @description Owner pastes the "BarberBase Integration Config" JSON copied from the Bhejna
		 *     portal. Go validates whatsapp_status == ACTIVE, quality_rating != RED, phone is
		 *     E.164, then test-sends via the Bhejna API. On success it stores ONLY
		 *     business_whatsapp_number, the AES-256-GCM encrypted api_key, the encrypted
		 *     webhook_secret, and sets locations.whatsapp_mode = 'own_number'. Returns the
		 *     webhook URL the owner must paste back into the Bhejna portal.
		 *     See: 06_bhejna_whatsapp.md — "Mode B One-Paste Onboarding Flow"
		 */
		post: operations['connectWhatsAppModeB'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/admin/locations/{location_id}/whatsapp/disconnect': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Disconnect a shop's own WABA (revert to shared platform number)
		 * @description Sets locations.whatsapp_mode = 'shared' and clears the encrypted credentials.
		 *     The location falls back to the platform Mode A number for all sends.
		 *     See: 06_bhejna_whatsapp.md — "Mode B One-Paste Onboarding Flow"
		 */
		post: operations['disconnectWhatsAppModeB'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/webhooks/bhejna/loc/{location_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Bhejna inbound webhook (Mode B — per-location)
		 * @description Mode B inbound webhook. The location_id path param resolves the shop's
		 *     encrypted webhook_secret BEFORE the payload is parsed; HMAC-SHA256 is verified
		 *     against the decrypted secret. On success, INSERT webhook_events (location_id
		 *     pre-filled) ON CONFLICT (source, external_event_id) DO NOTHING and return 200
		 *     immediately (Law 9). Processing is asynchronous (see 07_webhooks_outbox_workers.md).
		 *     Identical payload shapes to the Mode A webhook (see /webhooks/bhejna).
		 *     See: 06_bhejna_whatsapp.md — "Two Webhook Handlers"
		 */
		post: operations['receiveBhejnaWebhookModeB'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * Format: uuid
		 * @description UUID v7 (timestamp-sortable)
		 * @example 01906a2c-4f3e-7000-8000-000000000001
		 */
		UUIDv7: string;
		/**
		 * @description E.164 format
		 * @example +919876543210
		 */
		PhoneNumber: string;
		/**
		 * @description Monetary amount in paise (100 paise = 1 INR)
		 * @example 25000
		 */
		Paise: number;
		ErrorResponse: {
			/** @example QUEUE_SESSION_CLOSED */
			code: string;
			/** @example The queue is not accepting new entries right now */
			message: string;
			details?: {
				[key: string]: unknown;
			};
		};
		LocationStatus: {
			id: components['schemas']['UUIDv7'];
			/** @example Star Salon */
			name: string;
			/** @example star-salon/koramangala */
			slug: string;
			/** @enum {string} */
			shop_status: 'open' | 'closing_soon' | 'temporarily_closed' | 'closed';
			/** @description Derived from shop_status + queue_session.status */
			queue_open: boolean;
			/** @description Total waiting + called entries */
			queue_length: number;
			/** @description Sum of durations of all entries ahead in dispatch order */
			estimated_wait_minutes: number;
			business_hours_today: {
				/**
				 * Format: time
				 * @example 10:00
				 */
				opens_at?: string;
				/**
				 * Format: time
				 * @example 21:00
				 */
				closes_at?: string;
				is_open_today?: boolean;
			};
			/** Format: date-time */
			temporary_closure_ends_at?: string | null;
		};
		ServiceVariant: {
			id: components['schemas']['UUIDv7'];
			/** @example Mid Fade */
			name: string;
			description?: string | null;
			/** @example 25 */
			duration_minutes: number;
			price_paise: components['schemas']['Paise'];
			allow_walk_in: boolean;
			allow_appointment: boolean;
			requires_appointment: boolean;
			/** @description Flag for surfacing in highlights */
			is_popular?: boolean;
		};
		ServiceGroup: {
			id: components['schemas']['UUIDv7'];
			/** @example Fade */
			name: string;
			description?: string | null;
			variants: components['schemas']['ServiceVariant'][];
		};
		ServiceCategory: {
			id: components['schemas']['UUIDv7'];
			/** @example Hair */
			name: string;
			/** @enum {string} */
			gender: 'men' | 'women' | 'unisex';
			sort_order?: number;
			groups: components['schemas']['ServiceGroup'][];
		};
		ServiceCatalog: {
			location_id: components['schemas']['UUIDv7'];
			/** @enum {string} */
			display_mode: 'flat' | 'grouped' | 'hierarchical';
			categories: components['schemas']['ServiceCategory'][];
		};
		BookingOptions: {
			total_duration_minutes: number;
			total_price_paise: components['schemas']['Paise'];
			allowed_entry_methods: ('walk_in' | 'appointment')[];
			/** @enum {string|null} */
			blocked_reason?:
				| 'shop_closed'
				| 'queue_full'
				| 'requires_appointment'
				| 'closing_time_exceeded'
				| null;
			queue_length?: number;
			estimated_wait_minutes?: number;
		};
		/** @description Safe customer-facing view. No PII of other customers. */
		QueueEntryPublic: {
			id: components['schemas']['UUIDv7'];
			/** @example 18 */
			token_number: number;
			/** @enum {string} */
			state:
				| 'waiting'
				| 'called'
				| 'in_progress'
				| 'completed'
				| 'skipped'
				| 'no_show'
				| 'cancelled'
				| 'expired';
			/** @enum {string} */
			presence_state: 'remote' | 'notified' | 'on_the_way' | 'arrived' | 'snoozed' | 'unknown';
			/** @description Number of dispatchable arrived entries ahead */
			position_ahead: number;
			estimated_wait_minutes: number;
			services: {
				name?: string;
				duration_minutes?: number;
			}[];
			/** @default 1 */
			party_size: number;
			/** Format: date-time */
			magic_link_expires_at?: string;
			shop_name?: string;
			location_name?: string;
		};
		/** @description Full staff-facing view including customer info and presence */
		QueueEntryStaff: {
			id: components['schemas']['UUIDv7'];
			token_number: number;
			/** @enum {string} */
			state:
				| 'waiting'
				| 'called'
				| 'in_progress'
				| 'completed'
				| 'skipped'
				| 'no_show'
				| 'cancelled'
				| 'expired';
			/** @enum {string} */
			presence_state: 'remote' | 'notified' | 'on_the_way' | 'arrived' | 'snoozed' | 'unknown';
			is_dispatchable: boolean;
			customer: {
				id?: components['schemas']['UUIDv7'];
				name?: string | null;
				/** @description Last 4 digits shown e.g. "+91 XXXX XX4567" */
				phone_masked?: string | null;
				/** @description Total historical visits at this location */
				visit_count?: number;
				/** @description Staff-visible preference notes */
				notes?: string[];
			};
			services: {
				name?: string;
				duration_minutes?: number;
				price_paise?: components['schemas']['Paise'];
			}[];
			total_duration_minutes: number;
			party_size?: number;
			requested_barber_id?: components['schemas']['UUIDv7'];
			assigned_barber_id?: components['schemas']['UUIDv7'];
			/** Format: date-time */
			joined_at: string;
			/** Format: date-time */
			called_at?: string | null;
			/** Format: date-time */
			started_at?: string | null;
			/** @description Set by watchdog e.g. "called_10min" or "in_progress_overrun" */
			stale_warning?: string | null;
		};
		/** @description Full live queue for staff dashboard */
		QueueSnapshot: {
			queue_session_id: components['schemas']['UUIDv7'];
			/** @description Monotonically increasing. SSE clients compare this to decide if fetch is needed. */
			queue_version: number;
			/** Format: date */
			business_date: string;
			/** @enum {string} */
			session_status: 'active' | 'paused' | 'ending' | 'closed';
			entries: components['schemas']['QueueEntryStaff'][];
		};
		AppointmentSlot: {
			/**
			 * Format: time
			 * @example 11:00
			 */
			time: string;
			available: boolean;
			/**
			 * Format: time
			 * @example 11:40
			 */
			estimated_end_time: string;
			reason_unavailable?: string | null;
		};
		AppointmentResponse: {
			id: components['schemas']['UUIDv7'];
			/** Format: date-time */
			scheduled_start_at: string;
			/** @enum {string} */
			status: 'scheduled' | 'checked_in' | 'cancelled' | 'no_show';
			services: {
				name?: string;
				duration_minutes?: number;
			}[];
			total_duration_minutes?: number;
			total_price_paise?: components['schemas']['Paise'];
			/** Format: uri */
			magic_link: string;
		};
		CheckoutRequest: {
			queue_entry_id: components['schemas']['UUIDv7'];
			/** @default 0 */
			discount_amount_paise: components['schemas']['Paise'];
			discount_reason?: string | null;
			/** @description Products sold at checkout (beard oil etc). Does not affect queue duration. */
			product_line_items?: {
				product_id: components['schemas']['UUIDv7'];
				quantity: number;
			}[];
			/** @description Supports split payment. Sum must equal total_amount_paise. */
			payment_lines: {
				/** @enum {string} */
				method: 'cash' | 'upi' | 'card' | 'unpaid' | 'complimentary';
				amount_paise: components['schemas']['Paise'];
				/** @description UPI transaction ID, entered manually by staff */
				provider_reference_id?: string | null;
			}[];
		};
		CheckoutResponse: {
			visit_id: components['schemas']['UUIDv7'];
			subtotal_amount_paise?: components['schemas']['Paise'];
			discount_amount_paise?: components['schemas']['Paise'];
			total_amount_paise: components['schemas']['Paise'];
			/** @enum {string} */
			payment_status: 'paid' | 'unpaid' | 'complimentary';
			/** @description true if WhatsApp feedback request was queued in outbox */
			feedback_scheduled: boolean;
		};
		StaffMember: {
			id: components['schemas']['UUIDv7'];
			name: string;
			/** @enum {string} */
			role: 'owner' | 'manager' | 'barber';
			/** @enum {string} */
			status: 'idle' | 'cutting' | 'break' | 'offline';
			current_entry_id?: components['schemas']['UUIDv7'];
		};
		DailyAnalytics: {
			/** Format: date */
			business_date: string;
			total_visits: number;
			total_revenue_paise: components['schemas']['Paise'];
			average_wait_minutes?: number;
			no_show_count?: number;
			cancelled_count?: number;
			barber_breakdown: {
				barber_id?: components['schemas']['UUIDv7'];
				barber_name?: string;
				visits_completed?: number;
				revenue_paise?: components['schemas']['Paise'];
				average_service_minutes?: number;
			}[];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getLocationStatus: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Location status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LocationStatus'];
				};
			};
			/** @description Location not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getServiceCatalog: {
		parameters: {
			query?: {
				gender?: 'men' | 'women' | 'unisex' | 'all';
				/** @description Filter to a single category */
				category_id?: components['schemas']['UUIDv7'];
			};
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service catalog */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceCatalog'];
				};
			};
		};
	};
	searchServiceVariants: {
		parameters: {
			query: {
				q: string;
			};
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Matching variants */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						results?: (components['schemas']['ServiceVariant'] & {
							group_name?: string;
							category_name?: string;
						})[];
					};
				};
			};
		};
	};
	resolveBookingOptions: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					variant_ids: components['schemas']['UUIDv7'][];
					/** @default 1 */
					party_size?: number;
				};
			};
		};
		responses: {
			/** @description Booking options with computed totals */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BookingOptions'];
				};
			};
		};
	};
	createCheckinIntent: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					variant_ids: components['schemas']['UUIDv7'][];
					/** @default 1 */
					party_size?: number;
					/** @description Optional. Carried into the intent and onto the queue_entry at resolution. */
					customer_name?: string | null;
				};
			};
		};
		responses: {
			/** @description Intent created. Open deep_link to hand the session to WhatsApp. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						intent_id: components['schemas']['UUIDv7'];
						/**
						 * @description 6-char shortcode echoed in the WhatsApp JOIN message body.
						 * @example JN8K4P
						 */
						token_code: string;
						/**
						 * Format: uri
						 * @description wa.me link to the location's WhatsApp number (Mode B business
						 *     number, else the platform number for Mode A), pre-filled with
						 *     the JOIN command.
						 * @example https://wa.me/+912212345678?text=JOIN%20STAR-SALON%20JN8K4P
						 */
						deep_link: string;
						/**
						 * Format: date-time
						 * @description Intent expiry (created_at + 23h). After this, resolution returns 422.
						 */
						expires_at: string;
					};
				};
			};
			/** @description Location not found or not active */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Walk-in not available for these services right now (booking resolver blocked) */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getAppointmentSlots: {
		parameters: {
			query: {
				date: string;
				variant_ids: components['schemas']['UUIDv7'][];
			};
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Available slots */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** Format: date */
						date?: string;
						total_duration_minutes?: number;
						slots?: components['schemas']['AppointmentSlot'][];
					};
				};
			};
		};
	};
	requestStaffOTP: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					phone_number: components['schemas']['PhoneNumber'];
				};
			};
		};
		responses: {
			/** @description OTP sent */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** @example OTP sent to your WhatsApp */
						message?: string;
						/** @example 300 */
						expires_in_seconds?: number;
					};
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	verifyStaffOTP: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					phone_number: components['schemas']['PhoneNumber'];
					otp: string;
				};
			};
		};
		responses: {
			/** @description JWT issued. Set as httpOnly cookie by BFF. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						staff_member_id: components['schemas']['UUIDv7'];
						name: string;
						/** @enum {string} */
						role: 'owner' | 'manager' | 'barber';
						location_id: components['schemas']['UUIDv7'];
						tenant_id?: components['schemas']['UUIDv7'];
					};
				};
			};
			/** @description Invalid or expired OTP */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	refreshStaffToken: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description New access token issued */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Refresh token expired or invalid. Staff must re-login. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	joinQueue: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					location_id: components['schemas']['UUIDv7'];
					variant_ids: components['schemas']['UUIDv7'][];
					/** @default 1 */
					party_size?: number;
					/** @description Optional. Barber sees this on dashboard. */
					customer_name?: string | null;
					/**
					 * @description Provided when customer joins via web OTP path.
					 *     Null when joining via WhatsApp (phone resolved from Bhejna webhook).
					 */
					phone_number?: components['schemas']['PhoneNumber'];
					/**
					 * @description Provided by Bhejna webhook resolution. Never sent by browser directly.
					 *     Stored in customer_identities. Phone number is the canonical sending address.
					 */
					bsuid?: string | null;
					/** @description Only respected if location.queue_routing_mode = hybrid or barber_specific */
					requested_barber_id?: components['schemas']['UUIDv7'];
					/**
					 * Format: uuid
					 * @description UUIDv4 generated by client. Prevents double-join on network retry.
					 */
					idempotency_key: string;
					/** @enum {string} */
					initiated_via: 'whatsapp' | 'web_form' | 'staff_dashboard' | 'ai_agent';
				};
			};
		};
		responses: {
			/** @description Successfully joined or idempotent duplicate (returns existing entry) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						queue_entry: components['schemas']['QueueEntryPublic'];
						/** @description Signed token. Browser stores this. Also sent via WhatsApp. */
						magic_link_token: string;
						/**
						 * Format: uri
						 * @example https://barbers.app/q/status?t=eyJ...
						 */
						magic_link_url?: string;
						/** @description false if customer has no phone number (anonymous walk-in) */
						whatsapp_sent: boolean;
					};
				};
			};
			/** @description Customer already has an active entry at this location */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'] & {
						existing_entry?: components['schemas']['QueueEntryPublic'];
					};
				};
			};
			/** @description Booking resolver blocked this join (shop closed, queue full, requires appointment) */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	bookAppointment: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					location_id: components['schemas']['UUIDv7'];
					variant_ids: components['schemas']['UUIDv7'][];
					/** @default 1 */
					party_size?: number;
					/** Format: date-time */
					scheduled_start_at: string;
					customer_name?: string | null;
					/** @description Required for appointment. WhatsApp confirmation sent here. */
					phone_number: components['schemas']['PhoneNumber'];
					requested_barber_id?: components['schemas']['UUIDv7'];
					/** Format: uuid */
					idempotency_key: string;
					/** @enum {string} */
					initiated_via?: 'whatsapp' | 'web_form' | 'staff_dashboard' | 'ai_agent';
				};
			};
		};
		responses: {
			/** @description Appointment booked */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AppointmentResponse'];
				};
			};
			/** @description Slot no longer available */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getMyQueueStatus: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current queue status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueEntryPublic'];
				};
			};
			/** @description Invalid or expired session token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Entry not found or already completed/cancelled */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	confirmOnTheWay: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Presence updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** @example on_the_way */
						presence_state?: string;
						/** @example Great! Head over to Star Salon when ready. */
						message?: string;
					};
				};
			};
			/** @description Invalid transition (already arrived, snoozed, or completed) */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	confirmArrival: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @enum {string} */
					method: 'pin' | 'geolocation' | 'nfc';
					/** @description Required when method = pin */
					pin?: string;
					/**
					 * Format: double
					 * @description Required when method = geolocation
					 */
					latitude?: number;
					/**
					 * Format: double
					 * @description Required when method = geolocation
					 */
					longitude?: number;
					/** @description Browser-reported GPS accuracy. Go rejects if > 150m. */
					accuracy_metres?: number;
					/** @description Required when method = nfc. Signed payload from NFC tag. */
					nfc_token?: string;
				};
			};
		};
		responses: {
			/** @description Arrival confirmed */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** @example arrived */
						presence_state?: string;
						/** @example Welcome! You are next in line. */
						message?: string;
					};
				};
			};
			/** @description Incorrect PIN or invalid NFC token */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'] & {
						attempts_remaining?: number;
					};
				};
			};
			/** @description GPS accuracy too low. Fallback to PIN. */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	cancelMyEntry: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Entry cancelled */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Cannot cancel in current state (in_progress) */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	submitFeedback: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					rating: number;
					comment?: string | null;
				};
			};
		};
		responses: {
			/** @description Feedback recorded */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Feedback already submitted for this visit */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	subscribeToQueueStream: {
		parameters: {
			query: {
				/** @description Staff JWT or Customer session token */
				token: string;
			};
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description SSE stream opened */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': string;
				};
			};
			/** @description Invalid token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getQueueSnapshot: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Full queue snapshot */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueSnapshot'];
				};
			};
		};
	};
	callNextCustomer: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Customer called */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueEntryStaff'];
				};
			};
			/** @description No dispatchable customers available */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'] & {
						/** @description Customers in queue but not yet arrived */
						waiting_remote_count?: number;
					};
				};
			};
		};
	};
	startService: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service started */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueEntryStaff'];
				};
			};
			/** @description Invalid state transition or customer not arrived (for direct start) */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	completeService: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CheckoutRequest'];
			};
		};
		responses: {
			/** @description Service completed and checkout recorded */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CheckoutResponse'];
				};
			};
			/** @description Entry not in in_progress state or payment sum mismatch */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	skipEntry: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Entry skipped */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	markNoShow: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Marked as no-show */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	reactivateEntry: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Entry reactivated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueEntryStaff'];
				};
			};
		};
	};
	staffConfirmArrival: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Arrival confirmed by staff */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	reassignBarber: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					new_barber_id: components['schemas']['UUIDv7'];
				};
			};
		};
		responses: {
			/** @description Reassigned */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	addWalkIn: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @description "Uncle", "Kid with dad", etc. */
					customer_name?: string | null;
					phone_number?: components['schemas']['PhoneNumber'];
					variant_ids: components['schemas']['UUIDv7'][];
					/** @default 1 */
					party_size?: number;
					requested_barber_id?: components['schemas']['UUIDv7'];
				};
			};
		};
		responses: {
			/** @description Walk-in added to queue */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueEntryStaff'];
				};
			};
		};
	};
	setShopStatus: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @enum {string} */
					status: 'open' | 'closing_soon' | 'temporarily_closed' | 'closed';
					/** @description Required for temporarily_closed. Options: 15, 30, 60, or null (manual reopen). */
					expires_in_minutes?: number | null;
					reason?: string | null;
					/**
					 * @description Required if closing with active queue entries.
					 * @enum {string|null}
					 */
					modal_action?: 'finish_remaining' | 'expire_remaining' | null;
				};
			};
		};
		responses: {
			/** @description Status updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Active entries exist. modal_action required. */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'] & {
						active_entry_count?: number;
					};
				};
			};
		};
	};
	updateBarberStatus: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				staff_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @enum {string} */
					status: 'idle' | 'cutting' | 'break' | 'offline';
				};
			};
		};
		responses: {
			/** @description Status updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getDailyAnalytics: {
		parameters: {
			query?: {
				date?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Daily analytics */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DailyAnalytics'];
				};
			};
		};
	};
	provisionTenant: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @example Star Salon */
					tenant_name: string;
					/**
					 * @description URL-safe globally unique tenant identifier. e.g. "star-salon"
					 * @example star-salon
					 */
					tenant_slug: string;
					/** @example Ravi Kumar */
					owner_name: string;
					owner_phone: components['schemas']['PhoneNumber'];
					/** @example Star Salon — Koramangala */
					location_name: string;
					/**
					 * @description Globally unique full slug in the form "tenant-slug/location-slug".
					 *     Must be prefixed with tenant_slug. e.g. "star-salon/koramangala"
					 * @example star-salon/koramangala
					 */
					location_slug: string;
					/** @example 12, 80 Feet Road, Koramangala, Bengaluru 560034 */
					address?: string;
					/**
					 * @default Asia/Kolkata
					 * @example Asia/Kolkata
					 */
					timezone?: string;
				};
			};
		};
		responses: {
			/** @description Tenant provisioned. arrival_pin must be noted — display once, then only readable from /staff/shop/status. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						tenant_id: components['schemas']['UUIDv7'];
						location_id: components['schemas']['UUIDv7'];
						owner_staff_member_id: components['schemas']['UUIDv7'];
						/**
						 * @description Plaintext PIN shown once. Laminate on counter. Staff dashboard shows it thereafter.
						 * @example 8362
						 */
						arrival_pin: string;
					};
				};
			};
			/** @description Missing or invalid X-Platform-Admin-Key */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description tenant_slug, location_slug, or owner_phone already exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createServiceVariant: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @example Hair */
					category_name: string;
					/**
					 * @default unisex
					 * @enum {string}
					 */
					category_gender?: 'men' | 'women' | 'unisex';
					/** @example Fade */
					group_name: string;
					/** @example Mid Fade */
					variant_name: string;
					duration_minutes: number;
					price_paise: components['schemas']['Paise'];
					/** @default true */
					allow_walk_in?: boolean;
					/** @default true */
					allow_appointment?: boolean;
					/** @default false */
					requires_appointment?: boolean;
					/** @default false */
					is_popular?: boolean;
				};
			};
		};
		responses: {
			/** @description Service variant created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceVariant'];
				};
			};
		};
	};
	updateServiceVariant: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
				variant_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					variant_name?: string;
					duration_minutes?: number;
					price_paise?: components['schemas']['Paise'];
					is_active?: boolean;
					is_popular?: boolean;
				};
			};
		};
		responses: {
			/** @description Updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	regenerateArrivalPin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description New PIN generated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/**
						 * @description Display once to owner. Then only accessible from /staff/shop/status.
						 * @example 8362
						 */
						new_pin?: string;
					};
				};
			};
		};
	};
	createStaffMember: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					name: string;
					phone_number: components['schemas']['PhoneNumber'];
					/** @enum {string} */
					role: 'manager' | 'barber';
				};
			};
		};
		responses: {
			/** @description Staff member created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	receiveBhejnaWebhook: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @description Used as external_event_id for idempotency */
					bhejna_event_id: string;
					/** @enum {string} */
					event_type: 'message.received' | 'flow.completed' | 'message.status';
					/** @enum {string} */
					channel: 'whatsapp';
					/** Format: date-time */
					received_at: string;
					/** @description Routes to correct tenant/location */
					business_phone_number: string;
					sender: {
						/** @description Primary canonical identity. Always required from Bhejna. */
						phone_number: components['schemas']['PhoneNumber'];
						/** @description Stored in customer_identities as supplementary lookup. Not used for sending. */
						bsuid?: string | null;
						display_name?: string | null;
					};
					message?: {
						meta_message_id?: string;
						/** @enum {string} */
						type?: 'text' | 'button' | 'interactive' | 'flow_response';
						body?: string | null;
						button_payload?: string | null;
						flow_response?: {
							[key: string]: unknown;
						} | null;
					};
				};
			};
		};
		responses: {
			/** @description Acknowledged. Always 200. Processing is async. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	agentGetShopInfo: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Shop info for agent */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status?: components['schemas']['LocationStatus'];
						/** @description Top 5 is_popular variants for quick suggestions */
						popular_services?: (components['schemas']['ServiceVariant'] & {
							group_name?: string;
							category_name?: string;
						})[];
					};
				};
			};
		};
	};
	agentJoinQueue: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					location_id: components['schemas']['UUIDv7'];
					variant_ids: components['schemas']['UUIDv7'][];
					phone_number: components['schemas']['PhoneNumber'];
					/** @default 1 */
					party_size?: number;
					customer_name?: string | null;
					/** Format: uuid */
					idempotency_key: string;
				};
			};
		};
		responses: {
			/** @description Joined */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueEntryPublic'];
				};
			};
			/** @description Already in queue */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Booking blocked */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	agentBookAppointment: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					location_id: components['schemas']['UUIDv7'];
					variant_ids: components['schemas']['UUIDv7'][];
					/** Format: date-time */
					scheduled_start_at: string;
					phone_number: components['schemas']['PhoneNumber'];
					/** @default 1 */
					party_size?: number;
					customer_name?: string | null;
					/** Format: uuid */
					idempotency_key: string;
				};
			};
		};
		responses: {
			/** @description Appointment booked */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AppointmentResponse'];
				};
			};
		};
	};
	agentGetCustomerStatus: {
		parameters: {
			query: {
				phone_number: components['schemas']['PhoneNumber'];
				location_id: components['schemas']['UUIDv7'];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Customer status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueEntryPublic'];
				};
			};
			/** @description No active entry found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	agentCancelEntry: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					phone_number: components['schemas']['PhoneNumber'];
					location_id: components['schemas']['UUIDv7'];
				};
			};
		};
		responses: {
			/** @description Cancelled */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No active entry */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Cannot cancel (in_progress) */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	subscribePush: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/**
					 * Format: uri
					 * @description FCM/APNs endpoint URL from W3C PushSubscription.endpoint
					 */
					endpoint: string;
					/** @description Base64url client EC public key (PushSubscription.getKey("p256dh")) */
					p256dh: string;
					/** @description Base64url 16-byte auth secret (PushSubscription.getKey("auth")) */
					auth: string;
				};
			};
		};
		responses: {
			/** @description Subscription stored */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	pushCallNext: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Customer called — return updated queue state for notification refresh */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						called_entry: components['schemas']['QueueEntryStaff'];
						/** @description Remaining arrived dispatchable entries after this call */
						waiting_arrived_count: number;
						estimated_wait_minutes: number;
					};
				};
			};
			/** @description PAT expired or signature invalid — Service Worker must show "Session expired" notification */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description PAT command mismatch (Law 20) */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No arrived dispatchable customers at this location */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'] & {
						/** @description Customers in queue but not yet arrived */
						waiting_remote_count?: number;
					};
				};
			};
			/** @description Rate limited (1 per 3s per staff member) — barber double-tapped, ignore */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	connectWhatsAppModeB: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		/** @description Config blob copied verbatim from the Bhejna Developer Settings page. */
		requestBody: {
			content: {
				'application/json': {
					/** @example 1 */
					bhejna_config_version: string;
					/** @description Validation/diagnostic only — not persisted. */
					waba_id?: string;
					phone_number: components['schemas']['PhoneNumber'];
					phone_number_id?: string;
					/** @description Stored AES-256-GCM encrypted in locations.bhejna_api_key_encrypted. */
					api_key: string;
					/** @description Stored AES-256-GCM encrypted in locations.bhejna_webhook_secret_encrypted. */
					webhook_secret: string;
					/** @description Must equal ACTIVE or connect is rejected. */
					whatsapp_status: string;
					/** @description Validation/diagnostic only — not persisted. */
					display_name?: string;
					/** @description Rejected if RED. Validation/diagnostic only — not persisted. */
					quality_rating?: string;
					/** @description Validation/diagnostic only — not persisted. */
					messaging_limit?: number;
				};
			};
		};
		responses: {
			/** @description Connected — returns the webhook URL to paste into the Bhejna portal */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** @enum {string} */
						whatsapp_mode: 'own_number';
						/**
						 * Format: uri
						 * @example https://api.barberbase.in/v1/webhooks/bhejna/loc/0190...
						 */
						webhook_url: string;
					};
				};
			};
			/** @description Validation failed (status not ACTIVE, quality RED, bad phone, or test-send failed) */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	disconnectWhatsAppModeB: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Disconnected — location reverted to shared platform number */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	receiveBhejnaWebhookModeB: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: components['schemas']['UUIDv7'];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': Record<string, never>;
			};
		};
		responses: {
			/** @description Accepted (always 200 after HMAC passes — never 5xx, Law 9) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description HMAC signature invalid */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description location_id not found or not in own_number mode */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
